Controllers films users
atroshchenkoya/java-filmorate pull request #2
Opened 2024-11-23 21:42 UTC by atroshchenkoya

pom отредактировал, добавил явную настройку плагина компилятора с указанием версии JDK, без этого он кидался в меня ошибкой

Module filmorate SDK 21 does not support source version 1.5.
Possible solutions:
Downgrade Project SDK in settings to 1.5 or compatible. Open project settings.
Upgrade language version in Maven build file to 21..

Тесты сделаны по-старому, без использования SpringBootTest и каких либо операций с контекстом приложения.

2024-11-24 21:28 UTC, NikolaiDem requested changes

2024-11-24 21:28 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getId() == 0 || !films.containsKey(film.getId())) {
Условие "!films.containsKey(film.getId())" не учитывает ли условие "film.getId() == 0"?

2024-11-24 21:28 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void validateFilm(Film film) {
Использование валидации с помощью аннотаций позволит избавиться от избыточного кода:
https://medium.com/@himani.prasad016/validations-in-spring-boot-e9948aa6286b

2024-11-24 21:28 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private void validateUser(User user) {
Использование валидации с помощью аннотаций позволит избавиться от избыточного кода:
https://medium.com/@himani.prasad016/validations-in-spring-boot-e9948aa6286b

2024-11-24 21:28 UTC, NikolaiDem commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +class FilmControllerTest {
Опционально: попробовать сделать mvс тесты:
https://habr.com/ru/companies/otus/articles/746414/

2024-11-24 21:28 UTC, NikolaiDem commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +class UserControllerTest {
Опционально: попробовать сделать mvс тесты:
https://habr.com/ru/companies/otus/articles/746414/

2024-11-24 21:28 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new NotFoundException(errorMessage);
(Пока опционально): контроллер бросает ошибку, но еще лучше еще создать класс обработчик исключений ExceptionHandler, который обработает исключение и сформирует json ответ с соответствующей ошибкой

2024-11-25 09:27 UTC, atroshchenkoya commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getId() == 0 || !films.containsKey(film.getId())) {
Учитывает. film.getId() == 0 я как кейс, когда не задан ID оставил, но когда он явно задан ноль - ошибка будет некорректная. Так что на другом уровне лучше с этим разбираться, если разбираться вообще. Убираю пока.

2024-11-25 10:12 UTC, atroshchenkoya commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void validateFilm(Film film) {
Почитал, добавил

2024-11-25 10:13 UTC, atroshchenkoya commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new NotFoundException(errorMessage);
Уже написанные тесты не пройдут, если этого не сделать, поэтому делаем:)

2024-11-25 11:32 UTC, atroshchenkoya commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private void validateUser(User user) {
Есть

2024-11-25 11:36 UTC, atroshchenkoya commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +class FilmControllerTest {
Добавил

2024-11-25 11:36 UTC, atroshchenkoya commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +class UserControllerTest {
Добавил

2024-11-25 12:07 UTC, atroshchenkoya commented
чекстайл не дает использовать текстовые блоки...

2024-11-25 20:06 UTC, NikolaiDem approved these changes

2024-11-25 20:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film create(@Validated @RequestBody Film film) {
@Valid

2024-11-26 11:04 UTC, atroshchenkoya commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film create(@Validated @RequestBody Film film) {
Интересная описка, зато теперь про группы валидации знаю

2024-11-26 11:08 UTC, merged