Add friends likes
atroshchenkoya/java-filmorate pull request #3
Opened 2024-12-07 21:18 UTC by atroshchenkoya

2024-12-09 09:09 UTC, NikolaiDem requested changes

2024-12-09 09:09 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        getFilmOrThrow(film.getId());
code smells:
метод что-то возвращает,но это значение нигде не используется
Аналогично для класса UserService

2024-12-09 09:09 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        userService.findById(userId);
code smells:
метод что-то возвращает,но это значение нигде не используется
можно использовать что-то подобное userService.checkUser(...)
аналогично в следующем методе

2024-12-09 09:09 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public Collection<Film> getPopularFilms(int count) {
Этот метод больше подходит для сервиса. Цель репозитория - CRUD операции
Аналогично для методов лайков

2024-12-09 09:09 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    public void addFriend(User user, User friend) {
Методы, связанные с друзьями, больше подходят для сервиса.
Цель репозитория - CRUD операции

2024-12-09 13:42 UTC, atroshchenkoya commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        getFilmOrThrow(film.getId());
Я попробовал зарефакторить этот кусок, он родился от того, что я проверку на несуществование на уровне сервиса решил делать, а не репозитория.

2024-12-09 13:42 UTC, atroshchenkoya commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        userService.findById(userId);
аналогично, вроде, поправил

2024-12-09 13:44 UTC, atroshchenkoya commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public Collection<Film> getPopularFilms(int count) {
Всю сервисную логику перенес в сервисы, только CRUD оставил у репозиториев + явное сохранение добавил, чтобы в будущем хранилище можно было менее безболезненно на другое поменять.

2024-12-09 13:44 UTC, atroshchenkoya commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    public void addFriend(User user, User friend) {
Всю сервисную логику перенес в сервисы, только CRUD оставил у репозиториев + явное сохранение добавил, чтобы в будущем хранилище можно было менее безболезненно на другое поменять.

2024-12-10 09:26 UTC, NikolaiDem approved these changes

2025-01-02 09:55 UTC, merged